name: Feedback
description: A request, idea, or general comment
title: "[Feedback] "
labels: ["feedback"]
body:
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: What you'd like to see, or anything else you want to pass along.
    validations:
      required: true
